---
apiVersion: "v1"
metadata:
  name: hawkular-apm
items:
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: hawkular-apm
  spec:
    tls:
      insecureEdgeTerminationPolicy: Allow
      termination: edge
    to:
      kind: Service
      name: hawkular-apm
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: hawkular-apm
  spec:
    replicas: 1
    selector:
      name: hawkular-apm
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: hawkular-apm
      spec:
        containers:
        - capabilities: {}
          env:
          - name: HAWKULAR_APM_ADMIN_USERNAME
            value: admin
          - name: HAWKULAR_APM_ADMIN_PASSWORD
            value: password
          image: jboss/hawkular-apm-server
          imagePullPolicy: IfNotPresent
          name: hawkular-apm
          resources:
            limits:
              memory: 2048Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          readinessProbe:
            timeoutSeconds: 5
            initialDelaySeconds: 20
            httpGet:
              path: "/hawkular/apm/status"
              port: 8080
          livenessProbe:
            timeoutSeconds: 5
            initialDelaySeconds: 20
            httpGet:
              path: "/hawkular/apm/status"
              port: 8080
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        serviceAccountName: hawkular-apm
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.hawkular-apm: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"hawkular-apm"}}'
    name: hawkular-apm
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: hawkular-apm
    creationTimestamp: null
    name: hawkular-apm
  spec:
    ports:
    - name: web
      nodePort: 0
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      name: hawkular-apm
    sessionAffinity: None
    type: ClusterIP
kind: "List"
